# Generated by Django 4.0.2 on 2022-02-24 05:04

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=64)),
                ('course_code', models.CharField(max_length=8)),
                ('course_credits', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('curriculum_name', models.CharField(max_length=64)),
                ('curriculum_year', models.SmallIntegerField()),
                ('courses', models.ManyToManyField(to='api.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(max_length=4)),
                ('section_syllabus', models.FileField(upload_to='syllabuses/')),
                ('section_term', models.CharField(max_length=11)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=128)),
                ('university_website', models.CharField(max_length=128)),
                ('university_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('institutional_domain', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Grade_stats',
            fields=[
                ('a_count', models.IntegerField()),
                ('b_count', models.IntegerField()),
                ('c_count', models.IntegerField()),
                ('d_count', models.IntegerField()),
                ('f_count', models.IntegerField()),
                ('p_count', models.IntegerField()),
                ('w_count', models.IntegerField()),
                ('ib_count', models.IntegerField()),
                ('ic_count', models.IntegerField()),
                ('id_count', models.IntegerField()),
                ('if_count', models.IntegerField()),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.section')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=46)),
                ('last_name', models.CharField(max_length=46)),
                ('year_of_admission', models.SmallIntegerField()),
                ('institutional_email', models.CharField(max_length=320)),
                ('password', models.TextField()),
                ('curriculums', models.ManyToManyField(to='api.Curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Member',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=46)),
                ('last_name', models.CharField(max_length=46)),
                ('institutional_email', models.CharField(max_length=320)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='enrolled_students',
            field=models.ManyToManyField(to='api.Student'),
        ),
        migrations.AddField(
            model_name='section',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff_member'),
        ),
        migrations.AddField(
            model_name='section',
            name='likes',
            field=models.ManyToManyField(related_name='section_likes', to='api.Student'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('praises', models.TextField()),
                ('criticism', models.TextField()),
                ('is_misplaced', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(related_name='feedback_likes', to='api.Student')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='university_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
    ]
