# Generated by Django 4.0.2 on 2022-02-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='feedback_likes', to='api.Student'),
        ),
        migrations.AlterField(
            model_name='section',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='section_likes', to='api.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='curriculums',
            field=models.ManyToManyField(blank=True, to='api.Curriculum'),
        ),
    ]
