# Generated by Django 4.0.2 on 2022-03-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curriculum_Course',
            new_name='Curriculum_Courses',
        ),
    ]
