# Generated by Django 4.0.2 on 2022-03-02 00:39

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_curriculum_course_curriculum_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
