# Generated by Django 4.0.2 on 2022-03-02 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_university_university_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='university_id',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='staff_member',
            old_name='department_id',
            new_name='department',
        ),
    ]
