# Generated by Django 4.0.2 on 2022-03-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_department_id_course_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum',
            old_name='department_id',
            new_name='department',
        ),
    ]
