# Generated by Django 4.0.2 on 2022-03-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculum_courses',
            old_name='courses',
            new_name='course',
        ),
    ]
