# Generated by Django 4.0.2 on 2022-03-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_courses_curriculum_courses_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff_member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='staff_member',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='staff_member',
            name='institutional_email',
            field=models.CharField(max_length=320, null=True),
        ),
    ]
