# Generated by Django 4.0.2 on 2022-03-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_staff_member_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='convalidated_courses',
            field=models.ManyToManyField(to='api.Course'),
        ),
    ]
