# Generated by Django 4.0.2 on 2022-03-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_convalidated_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='convalidated_courses',
            field=models.ManyToManyField(blank=True, to='api.Course'),
        ),
    ]
