# Generated by Django 4.0.2 on 2022-03-05 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_course_convalidated_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_obtained', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='enrolled_students',
        ),
        migrations.AddField(
            model_name='section',
            name='enrolled_students',
            field=models.ManyToManyField(through='api.Section_Students', to='api.Student'),
        ),
        migrations.AddField(
            model_name='section_students',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section'),
        ),
        migrations.AddField(
            model_name='section_students',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
