# Generated by Django 4.0.2 on 2022-03-06 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_section_students_alter_section_enrolled_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.AddField(
            model_name='feedback',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.staff_member'),
        ),
        migrations.AddField(
            model_name='section',
            name='instructors',
            field=models.ManyToManyField(to='api.Staff_Member'),
        ),
    ]
