# Generated by Django 4.0.2 on 2022-03-06 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_section_instructor_feedback_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.staff_member'),
        ),
    ]
