# Generated by Django 4.0.2 on 2022-03-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_staff_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_syllabus',
            field=models.FileField(null=True, upload_to='syllabuses/'),
        ),
    ]
