# Generated by Django 4.1.dev20220426063221 on 2022-04-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_grade_stats_a_count_alter_grade_stats_b_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_syllabus',
            field=models.TextField(null=True),
        ),
    ]
