# Generated by Django 4.1.dev20220508003043 on 2022-05-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_section_section_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='likes',
        ),
        migrations.AddField(
            model_name='feedback',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='feedback_reports', to='api.student'),
        ),
    ]
