# Generated by Django 4.1.dev20220508003043 on 2022-05-08 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_section_likes_feedback_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='reports',
        ),
        migrations.CreateModel(
            name='Feedback_Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feedback')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
