from api.models import course 
from api.models import curriculum 
from api.models import department
from api.models import feedback
from api.models import grade_stats
from api.models import section
from api.models import staff_member 
from api.models import student
from api.models import university 